[workspace]

members = [
	"vorago-reb1-rs",
	"va108xx-rs",
	"va108xx-hal-rs"
]

[profile.dev]
lto = false
debug = true

[profile.release]
# Can be problematic for debugging
lto = true
debug = true
opt-level = 's'
