[workspace]

members = [
	"vorago-reb1-rs",
	"va108xx",
	"va108xx-hal",
	"max116xx-10bit",
]

[profile.dev]
lto = false
debug = true

[profile.release]
# Can be problematic for debugging
lto = true
debug = true
opt-level = 's'
